version: '3.4'

services:
  eschool.postgres:
    container_name: eschool.postgres
    image: postgres:13
    ports:
      - "5500:5432"
    environment:
      - POSTGRES_PASSWORD=Password123
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data

  eschool.rabbitmq:
    container_name: eschool.rabbitmq
    image: rabbitmq:3.8.9-management
    ports:
      - "5700:5672"
      - "5600:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - eschool_network
        
volumes:
  postgres_data:
  rabbitmq_data:

networks:
  eschool_network: