version: '3.4'

services:
  eschool.apigateway:
    image: ${DOCKER_REGISTRY-}eschoolapigateway
    build:
      context: .
      dockerfile: src/services/apigateway/ESchool.ApiGateway/Dockerfile

  eschool.classregister.api:
    image: ${DOCKER_REGISTRY-}eschoolclassregisterapi
    build:
      context: .
      dockerfile: src/services/classregister/ESchool.ClassRegister.Api/Dockerfile


  eschool.homeassignments.api:
    image: ${DOCKER_REGISTRY-}eschoolhomeassignmentsapi
    build:
      context: .
      dockerfile: src/services/homeassignments/ESchool.HomeAssignments.Api/Dockerfile


  eschool.identityprovider:
    image: ${DOCKER_REGISTRY-}eschoolidentityprovider
    build:
      context: .
      dockerfile: src/services/identityprovider/ESchool.IdentityProvider/Dockerfile


  eschool.testing.api:
    image: ${DOCKER_REGISTRY-}eschooltestingapi
    build:
      context: .
      dockerfile: src/services/testing/ESchool.Testing.Api/Dockerfile
      
  eschool.messaging.api:
    image: ${DOCKER_REGISTRY-}eschoolmessagingapi
    build:
      context: .
      dockerfile: src/services/messaging/ESchool.Messaging.Api/Dockerfile

  eschool.postgres:
    container_name: eschool.postgres
    image: postgres:13

  eschool.rabbitmq:
    container_name: eschool.rabbitmq
    image: rabbitmq:3.8.9-management