// <auto-generated />
using System;
using ESchool.ClassRegister.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ESchool.ClassRegister.Domain.Migrations
{
    [DbContext(typeof(ClassRegisterContext))]
    [Migration("20210228121004_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Class", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DidFinish")
                        .HasColumnType("bit");

                    b.Property<Guid?>("HeadTeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassTypeId");

                    b.HasIndex("HeadTeacherId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.ClassRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ClassRooms");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.ClassSchoolYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolYearId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SchoolYearId");

                    b.HasIndex("ClassId", "SchoolYearId")
                        .IsUnique();

                    b.ToTable("ClassSchoolYears");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.ClassType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingGrade")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ClassTypes");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Grading.Grade", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("KindId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.Property<DateTime>("WrittenIn")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClassSubjectId");

                    b.HasIndex("KindId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Grades");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Grading.GradeKind", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("AverageMultiplier")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("GradeKinds");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Messaging.Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SenderUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Subject")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SenderUserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Messaging.UserMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("UserId");

                    b.ToTable("UserMessages");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SchoolYear", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndOfFirstHalf")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("SchoolYears");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Subject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Absence", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AbsenceState")
                        .HasColumnType("int");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.HasIndex("StudentId");

                    b.ToTable("Absences");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassSchoolYearId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassSchoolYearId");

                    b.HasIndex("SubjectId");

                    b.ToTable("ClassSchoolYearSubjects");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubjectTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassSchoolYearSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ClassSchoolYearSubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("GroupTeachers");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.HomeWork", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LessonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LessonId");

                    b.ToTable("HomeWorks");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Canceled")
                        .HasColumnType("bit");

                    b.Property<Guid>("ClassRoomId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ClassSchoolYearSubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndsAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("LessonNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartsAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClassRoomId");

                    b.HasIndex("ClassSchoolYearSubjectId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.SubjectTeacher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeacherId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SubjectId");

                    b.HasIndex("TeacherId");

                    b.ToTable("SubjectTeachers");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.StudentParent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.HasIndex("StudentId");

                    b.ToTable("StudentParent");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.UserBase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("UserBases");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UserBase");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Administrator", b =>
                {
                    b.HasBaseType("ESchool.ClassRegister.Domain.Entities.Users.UserBase");

                    b.HasDiscriminator().HasValue("Administrator");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Parent", b =>
                {
                    b.HasBaseType("ESchool.ClassRegister.Domain.Entities.Users.UserBase");

                    b.HasDiscriminator().HasValue("Parent");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Student", b =>
                {
                    b.HasBaseType("ESchool.ClassRegister.Domain.Entities.Users.UserBase");

                    b.Property<Guid?>("ClassId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("StudentIdentificationNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ClassId");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Teacher", b =>
                {
                    b.HasBaseType("ESchool.ClassRegister.Domain.Entities.Users.UserBase");

                    b.Property<Guid?>("CurrentClassId")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CurrentClassId")
                        .IsUnique()
                        .HasFilter("[CurrentClassId] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Teacher");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Class", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.ClassType", "ClassType")
                        .WithMany()
                        .HasForeignKey("ClassTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Teacher", "HeadTeacher")
                        .WithMany("PreviousClasses")
                        .HasForeignKey("HeadTeacherId");

                    b.Navigation("ClassType");

                    b.Navigation("HeadTeacher");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.ClassSchoolYear", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Class", "Class")
                        .WithMany("ClassSchoolYears")
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.SchoolYear", "SchoolYear")
                        .WithMany("ClassSchoolYears")
                        .HasForeignKey("SchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("SchoolYear");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Grading.Grade", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubject", "ClassSchoolYearSubject")
                        .WithMany()
                        .HasForeignKey("ClassSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Grading.GradeKind", "Kind")
                        .WithMany()
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Student", "Student")
                        .WithMany("Grades")
                        .HasForeignKey("StudentId");

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Teacher", "Teacher")
                        .WithMany()
                        .HasForeignKey("TeacherId");

                    b.Navigation("ClassSchoolYearSubject");

                    b.Navigation("Kind");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Messaging.Message", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.UserBase", "SenderUser")
                        .WithMany("SentMessages")
                        .HasForeignKey("SenderUserId");

                    b.Navigation("SenderUser");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Messaging.UserMessage", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Messaging.Message", "Message")
                        .WithMany("ReceiverUserMessages")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.UserBase", "User")
                        .WithMany("ReceivedMessages")
                        .HasForeignKey("UserId");

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Absence", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Lesson", "Lesson")
                        .WithMany("Absences")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Student", "Student")
                        .WithMany("Absences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubject", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.ClassSchoolYear", "ClassSchoolYear")
                        .WithMany("ClassSubjects")
                        .HasForeignKey("ClassSchoolYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Subject", "Subject")
                        .WithMany()
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchoolYear");

                    b.Navigation("Subject");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubjectTeacher", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubject", "ClassSchoolYearSubject")
                        .WithMany()
                        .HasForeignKey("ClassSchoolYearSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Teacher", "Teacher")
                        .WithMany("GroupTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassSchoolYearSubject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.HomeWork", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Lesson", "Lesson")
                        .WithMany("HomeWorks")
                        .HasForeignKey("LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Lesson", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.ClassRoom", "ClassRoom")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubject", "ClassSchoolYearSubject")
                        .WithMany("Lessons")
                        .HasForeignKey("ClassSchoolYearSubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClassRoom");

                    b.Navigation("ClassSchoolYearSubject");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.SubjectTeacher", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Subject", "Subject")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Teacher", "Teacher")
                        .WithMany("SubjectTeachers")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subject");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.StudentParent", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Parent", "Parent")
                        .WithMany("StudentParents")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Users.Student", "Student")
                        .WithMany("StudentParents")
                        .HasForeignKey("StudentId");

                    b.Navigation("Parent");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Student", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Class", "Class")
                        .WithMany("Students")
                        .HasForeignKey("ClassId");

                    b.Navigation("Class");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Teacher", b =>
                {
                    b.HasOne("ESchool.ClassRegister.Domain.Entities.Class", "CurrentClass")
                        .WithOne()
                        .HasForeignKey("ESchool.ClassRegister.Domain.Entities.Users.Teacher", "CurrentClassId");

                    b.Navigation("CurrentClass");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Class", b =>
                {
                    b.Navigation("ClassSchoolYears");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.ClassRoom", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.ClassSchoolYear", b =>
                {
                    b.Navigation("ClassSubjects");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Messaging.Message", b =>
                {
                    b.Navigation("ReceiverUserMessages");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SchoolYear", b =>
                {
                    b.Navigation("ClassSchoolYears");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Subject", b =>
                {
                    b.Navigation("SubjectTeachers");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.ClassSchoolYearSubject", b =>
                {
                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.SubjectManagement.Lesson", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("HomeWorks");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.UserBase", b =>
                {
                    b.Navigation("ReceivedMessages");

                    b.Navigation("SentMessages");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Parent", b =>
                {
                    b.Navigation("StudentParents");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Student", b =>
                {
                    b.Navigation("Absences");

                    b.Navigation("Grades");

                    b.Navigation("StudentParents");
                });

            modelBuilder.Entity("ESchool.ClassRegister.Domain.Entities.Users.Teacher", b =>
                {
                    b.Navigation("GroupTeachers");

                    b.Navigation("PreviousClasses");

                    b.Navigation("SubjectTeachers");
                });
#pragma warning restore 612, 618
        }
    }
}
