apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: idp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
  - hosts:
    - idp.eschool.kmlabz.com
    secretName: idp-tls-secret
  rules:
  - host: idp.eschool.kmlabz.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: identityprovider
            port:
              number: 80