apiVersion: v1
kind: ConfigMap
metadata:
  name: ocelot-config
data:
  ocelot.json: |
    {
      "Routes": [
        {
          "DownstreamPathTemplate": "/api/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "classregister",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/api/class-register/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Patch", "Delete" ]
        },
        {
          "DownstreamPathTemplate": "/swagger",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "classregister",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/swagger/classregister",
          "UpstreamHttpMethod": [ "Get" ]
        },
        {
          "DownstreamPathTemplate": "/api/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "homeassignments",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/api/home-assignments/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Patch", "Delete" ]
        },
        {
          "DownstreamPathTemplate": "/swagger",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "homeassignments",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/swagger/homeassignments",
          "UpstreamHttpMethod": [ "Get" ]
        },
        {
          "DownstreamPathTemplate": "/api/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "identityprovider",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/api/identity-provider/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Patch", "Delete" ]
        },
        {
          "DownstreamPathTemplate": "/swagger",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "identityprovider",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/swagger/identityprovider",
          "UpstreamHttpMethod": [ "Get" ]
        },
        {
          "DownstreamPathTemplate": "/api/{everything}",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "testing",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/api/testing/{everything}",
          "UpstreamHttpMethod": [ "Get", "Post", "Put", "Patch", "Delete" ]
        },
        {
          "DownstreamPathTemplate": "/swagger",
          "DownstreamScheme": "http",
          "DownstreamHostAndPorts": [
            {
              "Host": "testing",
              "Port": 80
            }
          ],
          "UpstreamPathTemplate": "/swagger/testing",
          "UpstreamHttpMethod": [ "Get" ]
        },
      ],
      "GlobalConfiguration": {
      "BaseUrl": "https://api.eschool.kmlabz.com"
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: eschool.azurecr.io/apigateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        volumeMounts:
          - mountPath: /app/ocelot.json
            name: config-volume
            subPath: ocelot.json
      volumes:
        - name: config-volume
          configMap:
            name: ocelot-config
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
spec:
  selector:
    app: apigateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
