apiVersion: apps/v1
kind: Deployment
metadata:
  name: classregister
spec:
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: classregister
  template:
    metadata:
      labels:
        app: classregister
    spec:
      containers:
      - name: classregister
        image: eschool.azurecr.io/classregister:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        - containerPort: 8080
        env:
          - name: Swagger__DocumentPath
            value: /class-register/swagger/{documentName}/swagger.json
          - name: RabbitMQ__Host
            value: amqp://rabbitmq
          - name: RabbitMQ__Username
            valueFrom:
              secretKeyRef:
                name: rabbitmqcredentials
                key: USERNAME
          - name: RabbitMQ__Password
            valueFrom:
              secretKeyRef:
                name: rabbitmqcredentials
                key: PASSWORD
          - name: Authentication__Authority
            value: http://identityprovider
          - name: Authentication__Audience
            value: classregister-api
          - name: Authentication__IdentityProviderUri
            value: https://idp.eschool.kmlabz.com
          - name: ConnectionStrings__DefaultConnection
            valueFrom:
              secretKeyRef:
                name: classregisterconnectionstrings
                key: CONNECTION_STRING
          - name: ConnectionStrings__MasterDbConnection
            valueFrom:
              secretKeyRef:
                name: classregisterconnectionstrings
                key: MASTERDB_CONNECTION_STRING
          - name: ConnectionStrings__ConnectionStringTemplate
            valueFrom:
              secretKeyRef:
                name: classregisterconnectionstrings
                key: CONNECTION_STRING_TEMPLATE
---
apiVersion: v1
kind: Service
metadata:
  name: classregister
spec:
  selector:
    app: classregister
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 8080
      targetPort: 8080