name: Build Home Assignments and Deploy to AKS

on:
  workflow_dispatch:
  push:
    branches:
      [ master ]
    paths:
      - "src/services/homeassignments/**"
      - "src/services/classregister/ESchool.ClassRegister.Interface/**"
      - "src/services/identityprovider/ESchool.IdentityProvider.Interface/**"
      - "src/services/identityprovider/ESchool.IdentityProvider.DefaultHandlers/**"
      - "src/libs/**"
      - "src/proto/classregister.proto"

env:
  REGISTRY_NAME: eschool
  CLUSTER_NAME: eschool
  CLUSTER_RESOURCE_GROUP: eschool
  APP_NAME: homeassignments
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@main
    
    - name: Log into Container registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ env.REGISTRY_NAME }}.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }} 
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Build HomeAssignments image
      run: |
        docker build . -f ./src/services/homeassignments/ESchool.HomeAssignments.Api/Dockerfile \
          -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }} \
          -t ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:latest
    
    - name: Push HomeAssignments image
      run: docker push ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}

    - name: Set AKS Context
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ secrets.AZURE_CREDENTIALS }}'
        cluster-name: ${{ env.CLUSTER_NAME }}
        resource-group: ${{ env.CLUSTER_RESOURCE_GROUP }}

    - name: Deploy Services to AKS
      uses: azure/k8s-deploy@v1
      with:
        manifests: |
          k8s/services/homeassignments.yaml
        images: |
          ${{ env.REGISTRY_NAME }}.azurecr.io/${{ env.APP_NAME }}:${{ github.sha }}
